package schedulespec

import (
	"archive/zip"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"hash"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
)

// NormalizeInputs defines portable, bundle-relative globs. Empty declarations
// retain whole-bundle convergence; ** matches zero or more path components.
func NormalizeInputs(inputs []string) ([]string, error) {
	out := append([]string(nil), inputs...)
	for _, pattern := range out {
		if pattern == "" || strings.Contains(pattern, "\\") || strings.HasPrefix(pattern, "/") {
			return nil, fmt.Errorf("inputs must be nonempty bundle-relative patterns: %q", pattern)
		}
		for _, part := range strings.Split(pattern, "/") {
			if part == ".." || part == "." || part == "" {
				return nil, fmt.Errorf("invalid input pattern %q", pattern)
			}
			if part != "**" {
				if _, err := path.Match(part, ""); err != nil {
					return nil, fmt.Errorf("invalid input pattern %q: %w", pattern, err)
				}
			}
		}
	}
	sort.Strings(out)
	dedup := out[:0]
	for _, pattern := range out {
		if len(dedup) == 0 || dedup[len(dedup)-1] != pattern {
			dedup = append(dedup, pattern)
		}
	}
	return dedup, nil
}

func matchInput(pattern, name string) bool {
	p, n := strings.Split(pattern, "/"), strings.Split(name, "/")
	var match func(int, int) bool
	match = func(i, j int) bool {
		if i == len(p) {
			return j == len(n)
		}
		if p[i] == "**" {
			return match(i+1, j) || j < len(n) && match(i, j+1)
		}
		if j == len(n) {
			return false
		}
		ok, _ := path.Match(p[i], n[j])
		return ok && match(i+1, j+1)
	}
	return match(0, 0)
}

// ProducerBundleIdentity preserves command-only fingerprints for unscoped
// schedules. A scoped identity includes the canonical declaration and a sorted
// inventory of names, modes and file hashes. Missing matches are retained in
// the declaration digest, so additions and deletions invalidate it.
func ProducerBundleIdentity(commandJSON, inputsJSON, bundleDir string) (canonical, fingerprint string, err error) {
	canonical, fingerprint, err = ProducerIdentity(commandJSON)
	if err != nil || inputsJSON == "" || inputsJSON == "[]" || inputsJSON == "null" {
		return
	}
	var inputs []string
	if err = json.Unmarshal([]byte(inputsJSON), &inputs); err != nil {
		return "", "", fmt.Errorf("decode producer inputs: %w", err)
	}
	inputs, err = NormalizeInputs(inputs)
	if err != nil {
		return "", "", err
	}
	if len(inputs) == 0 {
		return canonical, fingerprint, nil
	}
	root, err := filepath.EvalSymlinks(bundleDir)
	if err != nil {
		return "", "", fmt.Errorf("resolve producer bundle: %w", err)
	}
	h := sha256.New()
	declaration, _ := json.Marshal(struct {
		Version int
		Command string
		Inputs  []string
	}{1, canonical, inputs})
	h.Write(declaration)
	// Hash the retained accepted archive, excluding dependency installations
	// and files subsequently generated by producers.
	if filepath.Base(filepath.Dir(root)) == "versions" {
		archive := filepath.Join(filepath.Dir(filepath.Dir(root)), "bundles", filepath.Base(root)+".zip")
		return producerArchiveIdentity(canonical, inputs, archive, h)
	}
	err = filepath.WalkDir(root, func(file string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(root, file)
		if err != nil {
			return err
		}
		name := filepath.ToSlash(rel)
		matched := false
		for _, pattern := range inputs {
			if matchInput(pattern, name) {
				matched = true
				break
			}
		}
		if !matched {
			return nil
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("producer input %q must be a regular file", name)
		}
		f, err := os.Open(file)
		if err != nil {
			return err
		}
		fh := sha256.New()
		_, readErr := io.Copy(fh, f)
		closeErr := f.Close()
		if readErr != nil {
			return readErr
		}
		if closeErr != nil {
			return closeErr
		}
		// Encode each record separately to avoid ambiguous name/content boundaries.
		record, _ := json.Marshal(struct {
			Name string
			Mode uint32
			Hash string
		}{name, uint32(info.Mode().Perm()), hex.EncodeToString(fh.Sum(nil))})
		h.Write(record)
		return nil
	})
	if err != nil {
		return "", "", fmt.Errorf("hash producer inputs: %w", err)
	}
	return canonical, "inputs:sha256:" + hex.EncodeToString(h.Sum(nil)), nil
}

func producerArchiveIdentity(canonical string, inputs []string, archive string, h hash.Hash) (string, string, error) {
	r, err := zip.OpenReader(archive)
	if err != nil {
		return "", "", fmt.Errorf("read accepted producer bundle: %w", err)
	}
	defer r.Close()
	files := append([]*zip.File(nil), r.File...)
	sort.Slice(files, func(i, j int) bool { return files[i].Name < files[j].Name })
	for _, f := range files {
		if f.FileInfo().IsDir() {
			continue
		}
		name := path.Clean(f.Name)
		matched := false
		for _, pattern := range inputs {
			if matchInput(pattern, name) {
				matched = true
				break
			}
		}
		if !matched {
			continue
		}
		if !f.Mode().IsRegular() {
			return "", "", fmt.Errorf("producer input %q must be a regular file", name)
		}
		reader, err := f.Open()
		if err != nil {
			return "", "", err
		}
		fh := sha256.New()
		_, readErr := io.Copy(fh, reader)
		closeErr := reader.Close()
		if readErr != nil {
			return "", "", readErr
		}
		if closeErr != nil {
			return "", "", closeErr
		}
		record, _ := json.Marshal(struct {
			Name string
			Mode uint32
			Hash string
		}{name, uint32(f.Mode().Perm()), hex.EncodeToString(fh.Sum(nil))})
		h.Write(record)
	}
	return canonical, "inputs:sha256:" + hex.EncodeToString(h.Sum(nil)), nil
}
