package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/rvben/shinyhub/internal/db"
)

// emitFleetManifest renders a shinyhub-fleet.toml from the deployed apps.
// Apps are emitted in slug order for stable output. With sourceRoot != "" each
// app's source is "<sourceRoot>/<slug>" and the block is active, so the file
// is immediately plan-able when the on-disk layout is <sourceRoot>/<slug>/.
// With sourceRoot == "" the source line is left commented: an honest,
// explicitly-incomplete scaffold whose apps trip the existing pre-flight
// "source is required" check (a precise message, never a confusing parse
// error) until the operator sets each path.
func emitFleetManifest(fleetID, sourceRoot string, apps []db.App) string {
	sorted := append([]db.App(nil), apps...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Slug < sorted[j].Slug })

	var b strings.Builder
	b.WriteString("# shinyhub-fleet.toml - generated by 'shinyhub fleet init'.\n")
	b.WriteString("# Source of truth for which apps exist, their source, and their\n")
	b.WriteString("# fleet-managed config. Review before applying.\n")
	if sourceRoot == "" {
		b.WriteString("#\n")
		b.WriteString("# Every app below has its 'source' commented out; set each app's\n")
		b.WriteString("# source path and remove the leading '#' before this manifest\n")
		b.WriteString("# is valid. 'shinyhub fleet plan' lists the still-unset ones.\n")
	}
	b.WriteByte('\n')
	fmt.Fprintf(&b, "fleet_id = %s\n\n", tomlString(fleetID))

	root := strings.TrimRight(sourceRoot, "/")
	for _, a := range sorted {
		b.WriteString("[[app]]\n")
		fmt.Fprintf(&b, "slug       = %s\n", tomlString(a.Slug))
		if root != "" {
			fmt.Fprintf(&b, "source     = %s\n", tomlString(root+"/"+a.Slug))
		} else {
			fmt.Fprintf(&b, "# source   = %s   # REQUIRED: set the path, then remove the leading '#'\n",
				tomlString("./path/to/"+a.Slug))
		}
		vis := a.Access
		if vis == "" {
			vis = "private"
		}
		fmt.Fprintf(&b, "visibility = %s\n", tomlString(vis))

		var cfg []string
		if a.HibernateTimeoutMinutes != nil {
			cfg = append(cfg, fmt.Sprintf("hibernate_timeout_minutes = %d", *a.HibernateTimeoutMinutes))
		}
		if a.Replicas > 0 {
			cfg = append(cfg, fmt.Sprintf("replicas                  = %d", a.Replicas))
		}
		if a.MaxSessionsPerReplica > 0 {
			cfg = append(cfg, fmt.Sprintf("max_sessions_per_replica  = %d", a.MaxSessionsPerReplica))
		}
		if len(cfg) > 0 {
			b.WriteString("\n  [app.config]\n")
			for _, line := range cfg {
				fmt.Fprintf(&b, "  %s\n", line)
			}
		}
		b.WriteByte('\n')
	}
	return b.String()
}

// tomlString returns a TOML basic-string literal for s. Manifest values here
// (slugs, visibility, generated source paths) are simple, but escaping any
// embedded '"' or '\' keeps the emitter correct for arbitrary server data.
func tomlString(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}
